name: boost testing workflow

on: [push, workflow_dispatch]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install clang-format style checker"
        run: sudo apt install clang-format
      - name: "Run clang-format on source files"
        run: clang-format --dry-run -Werror src/*
      - name: "Run clang-format on test files"
        run: clang-format --dry-run -Werror tests/*.cpp
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install requirements"
        run: sudo apt install cmake libeigen3-dev libyaml-cpp-dev libboost-test-dev
      - name: "Build and make project"
        run: mkdir build && cd build && cmake .. && make -j
      - name: "Archive executable for preserving file permissions"
        run: tar -cvf build.tar build/
      - name: "Store build arifact"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar
          retention-days: 14
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install requirements"
        run: sudo apt install cmake libeigen3-dev libyaml-cpp-dev libboost-test-dev
      - name: "Download build"
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: "Unpack build artifact"
        run: tar -xf build.tar
      - name: "Run tests" 
        run: cd build && make test
